### ISSUE TITLE
prevent doubled data input of nesting box ID

### ISSUE THREAD

**Issue by gacsphere** [gacsphere/capstone-project#13]
## Value Proposition
As a user, I want to be saved from making mistakes during my data collection so that I have a valid result afterwards.
## Description
- [ ] Emergency message alerting the user to duplicate data entry for _Nistkasten ID_
## Acception Criteria
- [ ] Emergency message popping up if the user tries to enter a _Niskaten ID_ which already exists
## Tasks
- [ ] implement alert message on submit of form or on change of input if boxnumber already exists

**Comment by gacsphere** [comment]
Hi @kai-franke, thank you for your input! I changed the user story a bit, but I didn't get as specific as you asked, because I'm not sure yet how to implement this and which consequences and possible problems this may cause.

Now I want an emergency notification appearing if the user tries to enter a Nistkasten ID which already exists – maybe it's not even a message, I'm not sure yet. Maybe it disappears, when the user changes his input. Do you think it is still neccessary to define it in this story?

**Comment by kai-franke** [comment]
I think the most important thing is that your acceptance criteria are specific enough and I feel those are appropriate for this feature.

About the tasks: At some point you will have to deal with the specific ways to implement it, so this could be in the design phase now. 😉 
But I think it's okay for such a small feature if it's not planned in detail.

**Comment by gacsphere** [comment]
I would say, the way you describe it, is the perfect way, Kai. :ok_hand: It is definitely easier later, if I could just do the predefined tasks step by step. For me the first challenge in this user story is how to find out if a nesting box number already exists. Hmmm, I guess then, this is the very first task: find out if a nesting box number already exists.
