### ISSUE TITLE
Enhance user experience of form

### ISSUE THREAD

**Issue by gacsphere** [gacsphere/capstone-project#14]
## Value Proposition
As a user experience oriented developer, I want to provide a form which is easy to understand and easy to use  so that the user can concentrate on his work without getting disturbed by an interruptive process or unclear usage of the app.
## Description

![userstory9_form-ux](https://user-images.githubusercontent.com/109087424/197500184-2f151bfe-5229-494f-b6a5-198c8828fba9.png)

## Acception Criteria
- [ ] display default Values for date and time
- [ ] show most important input fields on top of form and less important input fields as last
## Tasks
- [ ] check over form structure
- [ ] rearrange order of inputs according to importance
- [ ] automate default Values for date and time
- [ ] refactor code

**Comment by CathrinTruchan** [comment]
Very nice user story, Gesa! One question: The save and reset button have the same color. Maybe it would be clearer for the user, if they would look different? (Or is that part of another user story?)

**Comment by gacsphere** [comment]
Thank you @CathrinTruchan, 
this is indeed a thing I want to change here and set the reset button style as secondary button. 
In this context there is another problem I didn't manage yet:
I want a second reset button `reset local information` on top of the form which resets only the inputs of date, time and location to its default values. With this specific reset button I'm not sure yet if it would be a primary button or secondary button.
But maybe I'll use the reset-everything button I already have and put it on top of the form.

**Comment by sebsch1337** [comment]
What is the form for? :) Maybe you can specify a bit more.

**Comment by gacsphere** [comment]
Hi @sebsch1337 , thank you for reviewing! I forgot to mention, that it's about the existing form which serves to add further entries of nestingboxes. I rewrote the value proposition. Do you think it's clearer now?

**Comment by sebsch1337** [comment]
Looks good now! :)
