### ISSUE TITLE
Sort cards by Date

### ISSUE THREAD

**Issue by gacsphere** [gacsphere/capstone-project#16]
## Value Proposition
As a user, I want my data structured so that I can classify data bundles as belonging to respective data collections.
## Description
Breaking down the data into lists sorted by date.
## Acception Criteria
- [ ] Data is bundled by date. => Cards are sorted by Date
## Tasks
- [ ] tasks to achieve the functionalities
- [ ] step by step
- [ ] to be executed by developer
