### ISSUE TITLE
EditCardForm as popup

### ISSUE THREAD

**Issue by gacsphere** [gacsphere/capstone-project#17]
## Value Proposition
As a user, when editing data, I don't want to get confused by too much information displayed on the screen. I want to stay focused on my task.
## Description

![userstory10_editCardForm-popup](https://user-images.githubusercontent.com/109087424/198039041-2bb7910d-205b-4f1e-bed1-0ee0e73e0b5f.png)

## Acception Criteria
- [ ] Display EditCardForm.
- [ ] Don't display further components on the same "visual level".
- [ ] The user can't get interactive with any other components besides the EditCardForm when EditCardForm is active.
## Tasks
- [ ] Style EditCardForm as a popup.

**Comment by kai-franke** [comment]
Dear @gacsphere , I like your story – especially because I, as a user myself, don't want to get confused either! 😄  

I just wonder if your tasks are sufficiently described. Do you already have all the functions and components needed for such a popup?

**Comment by gacsphere** [comment]
Thank you @kai-franke!
My problem often is, that I can't imagine everything that is needed. 
For this user story I would say I need the edit card form, and I got it from another user story. Do you have a hint, if there is something else that I haven't thought about yet?

**Comment by kai-franke** [comment]
I don't have such a feater myself yet, but Sebastian has already done it, for example:
https://github.com/sebsch1337/capstone-project/blob/main/components/Modal.js
