### ISSUE TITLE
Form validation

### ISSUE THREAD

**Issue by gacsphere** [gacsphere/capstone-project#18]
## Value Proposition
As a user, I would like to be protected from accidentally entering incorrect data in order to have valid data.
## Description
Alert is shown, when entered Data is not valid.
## Acception Criteria
- [ ] Form won't be sent if date lies in the future.
- [ ] Form won't be sent if latitude is not valid.
- [ ] Form won't be sent if longitude is not valid.
## Tasks
- [ ] Add validation for date.
- [ ] Add validation for longitude.
- [ ] Add validation for latitude.
