### ISSUE TITLE
Display card

### ISSUE THREAD

**Issue by gacsphere** [gacsphere/capstone-project#2]
## Value Proposition
As a user, I want to see the notes of a nesting box so that I know how many bats were in there at a specific time.
## Description
![30 batSCAN Copy 2_userstory0](https://user-images.githubusercontent.com/109087424/195828756-9385ef74-3a47-4cd6-9618-254023312f1d.png)
## Acception Criteria
- [ ] card is displayed
## Tasks
- [ ] create an array with one nesting-box-object in it
- [ ] render array to a card

**Comment by F-Kirchhoff** [comment]
This is a fantastic user story! Very clear acceptance criteria and tasks. If I would criticise one thing is that there is no reason in your value proposition. If you add one this one is perfect.

**Comment by ThomasF85** [comment]
Your array should be in a Javascript file, not a json file, for example:
nestingBoxes.js:
`export const nestingBoxes = [{...}, {...}]`
