### ISSUE TITLE
Map integration

### ISSUE THREAD

**Issue by gacsphere** [gacsphere/capstone-project#21]
## Value Proposition
As a user, I want to have a map in order to know where I am and where I can go.
## Description
*imagine a map*
## Acception Criteria
- [ ] display map
- [ ] display LocationMarker of current location

## Tasks
- [ ] install necessary packages 
- [ ] implement leaflet
- [ ] implement LocationMarker of current location
- [ ] implement navigation between nestingbox-list and map

**Comment by PhilippWeiss85** [comment]
Hi Gesa,
I would rewrite the VP a little bit (e.g.): As a user, I want to see on a map where I am so that I can navigate to the nestingBoxes around me.
Further the "navigation" task could be quite complicated (as Thomas said) because you have no route-api in leaflet. Maybe it is smart to leave that point for now?

**Comment by gacsphere** [comment]
Thank you @PhilippWeiss85,
I updated the VP, but I left out the nesting boxes as they are not shown on the map yet.
Thank you for the hint with the navigation! I have left this task out.
