### ISSUE TITLE
Link project data to the map

### ISSUE THREAD

**Issue by gacsphere** [gacsphere/capstone-project#23]
## Value Proposition
As a user, I want the data from my project be displayed on the map so that I have access to it via the map and see which data was saved and where the data was collected.
## Description
// Insert Wire Frame
## Acception Criteria
- [ ] Dummy data replaced with project data
- [ ] Add nestingboxes works 
- [ ] New added nestingboxes are shown on the map
- [ ] Popups show project data
## Tasks
- [ ] Delete dummy data from Map component
- [ ] Hand down props to Map component
- [ ] Map over nesting boxes array in Map component
- [ ] Customize Popup
- [ ] Add a customized marker icon
- [ ] Add a map icon as a reference for the navigation to the map

**Comment by Kheirah** [comment]
Looking good!
