### ISSUE TITLE
Edit nesting box data via map component

### ISSUE THREAD

**Issue by gacsphere** [gacsphere/capstone-project#24]
## Value Proposition
As a user I want to have the ability to access the editCardForm directly via the respective popup on the map so that I don't need to switch pages to access the editCardForm.
## Description

![userstory15_Map-edit](https://user-images.githubusercontent.com/109087424/199829846-d3fe2a81-3e06-4278-85d1-57aa72500bee.png)
![userstory17_Map-edit-2](https://user-images.githubusercontent.com/109087424/199830416-2d3ad095-40c6-4265-a6bd-970bfecdb1ed.png)

## Acception Criteria
- [ ] EditCardForm for respective nestingbox card is accessible via the popups on the map
## Tasks
- [ ] Add button/edit icon to popup opening editCardForm
- [ ] Style editCardForm as a popup to show it as an overlay to the map

**Comment by Kheirah** [comment]
Really cool feature!
