### ISSUE TITLE
Link card to respective location on map

### ISSUE THREAD

**Issue by gacsphere** [gacsphere/capstone-project#27]
## Value Proposition
As a user, I want each card link to the location on the map, so that I can see on the map where the respective data has been collected.
## Description
// Insert Wire Frame
## Acception Criteria
- [ ] A button on each card links to the respective location on the map
- [ ] When pressing the button, the map will be opened and the respective location will be focused
## Tasks
- [ ] Add a button to the card component
- [ ] Write a function that leads to the respective location where the data has been collected

**Comment by PhilippWeiss85** [comment]
Hi Gesa, love your story! Happy coding :)
