### ISSUE TITLE
Add new location by tapping on the map

### ISSUE THREAD

**Issue by gacsphere** [gacsphere/capstone-project#28]
## Value Proposition
As a user, I want add coordinates by choosing a point on the map so that I can easily add new locations.
## Description
// Insert Wire Frame
## Acception Criteria
- [ ] New location is added when tapping on the map
- [ ] Next step: EditCardForm opens, new location is editable and can be filled with necessary project data via the form

## Tasks
- [ ] tasks to achieve the functionalities
- [ ] step by step
- [ ] to be executed by developer

**Comment by Kheirah** [comment]
What happens to the map icon when I change the coordinates in the popup form? Does it get replaced to the new location and the view portion of the map changes to the new location as well?

**Comment by gacsphere** [comment]
Hmmm, you're right, there are some things I haven't thought about yet. If I had a form where I could enter some other coordinates like the ones I clicked, the icon position should change if the coordinates in the form are changed. But maybe I should consider to make the coordinates not editable in this case. I mean: if someone taps on the map, he wants to have the marker on the respective position. In each case I want the coordinates and date + time saved in the array like the other data objects.
I need to come back and work on this user story later on when I see clearer how this should work. Thank you for your input!!!
