### ISSUE TITLE
Display list of cards

### ISSUE THREAD

**Issue by gacsphere** [gacsphere/capstone-project#3]
## Value Proposition
As a user, I want to get an overview of all nesting boxes in order to know how many bats have been in each nesting box at a specific time.

## Description

![Image](https://user-images.githubusercontent.com/109087424/196456935-44e49f4f-4536-4fa2-9123-f3e07750049a.png)

## Acception Criteria
- [x] several cards should be listed
- [x] each card should display how many bats have been in each nesting box at a specific time

## Tasks
- [x] create new component for list of cards
- [x] add more nesting-box-objects to the array
- [x] map over the array to display each nesting-box-object as a card in a list of cards

**Comment by gacsphere** [comment]
At this point I'm not sure where the array is saved and accessed. Is it a "nesting-boxes-array" as a json-file in a db-folder?

**Comment by ThomasF85** [comment]
LGTM!
The array could be in any JavaScript file, e.g. a separate file for the array, or in a component file (outside of the component itself - meaning the `function MyComponent() {...}`)

**Comment by philmetscher** [comment]
Hey :) You should give your image a background. Otherwise it looks like this on GitHub for me (dark mode on)
![Bildschirmfoto 2022-10-17 um 11 11 46](https://user-images.githubusercontent.com/85338528/196138368-af7ff6c5-3966-480f-a62d-daa78d77249c.png)
