### ISSUE TITLE
General styling 

### ISSUE THREAD

**Issue by gacsphere** [gacsphere/capstone-project#32]
## Value Proposition
As a type of user, I want a good overview of the whole content so that I have a good understanding of the app and the data it provides.
## Description
// UX/UI & styling
## Acception Criteria
- [ ] App is easily understandable 
- [ ] The control of the app are obvious
## Tasks
- [ ] check responsiveness of layout
- [ ] organize reused styled components
- [ ] rework style where necessary
- [ ] clean up code

**Comment by philmetscher** [comment]
LGTM!
