### ISSUE TITLE
Display total amount of bats

### ISSUE THREAD

**Issue by gacsphere** [gacsphere/capstone-project#4]
## Value Proposition
As a user, I want to see the total amount of counted bats in all nesting boxes so that i don't have to calculate myself.
## Description

![userstory2](https://user-images.githubusercontent.com/109087424/195841014-3452f711-040d-467b-8ec4-3d0576a61f01.png)

## Acception Criteria
- [ ] total amount of bat count is displayed

## Tasks
- [ ] add sum function to calculate the total amount
- [ ] render component/display sum

**Comment by ThomasF85** [comment]
LGTM! In some other user stories you did not specify the task "create a new branch". You should create a new branch for every new feature, so I would either include that task in every story or in non (as you automatically create new branches for every story)
