### ISSUE TITLE
Header Component

### ISSUE THREAD

**Issue by gacsphere** [gacsphere/capstone-project#5]
## Value Proposition
As a user, I want to have some orientation within the app so that I know where I am.
## Description
![userstory3_header](https://user-images.githubusercontent.com/109087424/196130715-2a3b3eb7-4694-4ab0-ad62-ccc391d98054.png)
## Acception Criteria
- [ ] display header with app title
## Tasks
- [ ] create new branch
- [ ] create Header component
- [ ] implement Header component

**Comment by AHen-C0de** [comment]
This is a very short user story, that you might be able to implement in 30 minutes. If you want a code review after this user story, I would recommend to add some more tasks, but if you will just go on to the next story afterwards, this is fine.

**Comment by gacsphere** [comment]
Thank you Angela, you are right. I will postpone this issue then until I have some navigation.
