### ISSUE TITLE
Add cards – Form

### ISSUE THREAD

**Issue by gacsphere** [gacsphere/capstone-project#6]
## Value Proposition
As a user, I want to be able to enter further data so that I can use the app to track the stock at future observations.
## Description
![userstory6_button_to-add-cards-form](https://user-images.githubusercontent.com/109087424/196147281-37daa79f-c206-47ed-9b38-12319af8145c.png)
![userstory6_form_add-cards](https://user-images.githubusercontent.com/109087424/196147316-eb38c828-e82a-46e2-a0ed-0b6807eff231.png)

## Acception Criteria
- [ ] display a form with the necessary input fields for…
- [ ] … amount, date, time, place (Nistkasten Nr.), place (coordinates)
- [ ] a button to access the form
- [ ] a button to submit the form
- [ ] a button to exit the form
## Tasks
- [ ] create new Form component
- [ ] add input fields
- [ ] add labels for input fields
- [ ] add submit button which adds the data as a new card to the card-list

**Comment by Mark-Krensel** [comment]
Hello, I'm a bit confused with 1st picture. I guess this is how the data should look like once it was submitted. My second guess is that the big + button is for entering the form and the X button is for closing the form, but I don't understand where the submit-button is.
The scope is good I think :)
