### ISSUE TITLE
Edit card

### ISSUE THREAD

**Issue by gacsphere** [gacsphere/capstone-project#8]
## Value Proposition
As a user , I want to edit the data of my cards in order to update or correct the information.
## Description
![userstory8a_edit-card](https://user-images.githubusercontent.com/109087424/196444660-86ed89cc-da14-4a5f-82e3-3ba69774171f.png)
![userstory8b_edit-card](https://user-images.githubusercontent.com/109087424/196444673-986fd9d7-3c10-4f2e-9ae1-08a2cbcf71ea.png)
(The delete-button comes from a previous issue)
## Acception Criteria
- [x] Edit page, where cards can be edited
- [x] Some direction to edit page: icon on card in card-list or simply on tap/click (card)
## Tasks
- [x] Add card-edit page, where data can be edited
- [x] Add edit button to page
- [x] Add edit function

**Comment by Sukhpreet92** [comment]
looks good to me 👍
